# Generated by Django 4.2.10 on 2024-03-13 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('useremail', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('stid', models.IntegerField(primary_key=True, serialize=False)),
                ('stname', models.CharField(default=' ', max_length=100)),
                ('staddress', models.CharField(max_length=100)),
                ('stcity', models.CharField(max_length=50)),
                ('ststate', models.CharField(max_length=50)),
                ('stpost', models.CharField(max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
